name: Deploy the application
on: 
    push:
        branches:
            - main
jobs:
    imagebuild:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            
            - name: Set up Maven
              uses: stCarolas/setup-maven@v4.5
              with:
                maven-version: 3.8.1
            
            - name: check version of the maven
              run: |
                mvn --version

            - name: Build and create the war file with maven package
              run: |
                cd ./hello-world
                mvn clean package
            
            - name: run the docker file
              run: |
                docker build -t kethavenu6032/regapp:v1 -f ./hello-world/Dockerfile ./hello-world
            
            - name: login to the docker repo
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: push the images to the repository
              run: |
                docker push kethavenu6032/regapp:v1
                
