name: Job variables
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            my_password: ${{ steps.step1.outputs.password }}
        steps:
            - name: setting the variable
              id: step1
              run: echo "password=${{ vars.MY_NAME }}" >> $GITHUB_OUTPUT
            
            - name: printing the vars
              run: echo ${{ steps.step1.outputs.password }}
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: printing the job variable
              run: echo ${{ needs.build.outputs.my_password }}